In [2]:
import numpy as np
import matplotlib.pyplot as plt

#### practice with real world data

In [5]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
import numpy as np

sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print("======zomato sales analysis======")
print("\nshape : ",sales_data.shape)
print("sample data for 1st 3 restaurants:",sales_data[0:3])


======zomato sales analysis======

shape :  (5, 5)
sample data for 1st 3 restaurants: [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [8]:
#total sales per year
print(np.sum(sales_data,axis = 0))
yearly_total = np.sum(sales_data[:, 1:] , axis = 0)
print(yearly_total)
total=np.sum(yearly_total[0:5])
print(total)

#->>> axis = 0("goes down") , ->>> axis = 1("goes across")

#minimum sales
minimum_sales = np.min(sales_data[:,1:], axis = 1 )
print(minimum_sales)
#max sales per year
max_sales = np.max(sales_data[:,1:] , axis = 0)
print(max_sales)
#average sales of restaurant
avg_sales = np.mean(sales_data[:,1:],axis=1)
print(avg_sales)
#cumulativesum
cumsum = np.cumsum(sales_data[:,1:] , axis =1)
print(cumsum)

plt.figure(figsize = (10,6))
plt.plot(np.mean(cumsum,axis=0))
plt.title("average cumulative sales across all restaurants")
plt.xlabel("years")
plt.ylabel("sales")
plt.grid(True)
plt.show()

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
4080000
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]
[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [ ]:
#vector operations
vector1 = np.array([1,2,3,4])
vector2 = np.array([6,7,8,9])

print("addition of vectors : ",vector1 + vector2)
print("Multiplication of vectors : ",vector1 * vector2)
print("dot product",np.dot(vector1,vector2))

#to convert array to upppercase letters:
restaurant_types = np.array(["biryani","pizza","chicken"])
vectorized_upper = np.vectorize(str.upper)
print("In Upper case : ",vectorized_upper(restaurant_types))

#broadcasting
monthly_avg = sales_data[:,1:] / 12
print(monthly_avg)


addition of vectors :  [ 7  9 11 13]
Multiplication of vectors :  [ 6 14 24 36]
dot product 80
In Upper case :  ['BIRYANI' 'PIZZA' 'CHICKEN']
[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
