#### Numpy Array Operations

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print("basic slicing : ",arr[3:6])
print("with steping : ",arr[1:6:2])
print("with negative : ",arr[-3])

basic slicing :  [4 5 6]
with steping :  [2 4 6]
with negative :  4


In [ ]:
arr_2d = np.array([[1,2,3], # here 1st index is [4,5,6]
                  [4,5,6],
                  [7,8,9]])
print("specific element : ", arr_2d[1,2])
print("Entire row : ",arr_2d[2])
print("entire column : ",arr_2d[:,1])

specific element :  6
Entire row :  [7 8 9]
entire column :  [2 5 8]


### sorting

In [4]:
unsorted = np.array([3,2,4,5,31,1])
print("sorted array ",np.sort(unsorted))

arr_2d = np.array([[3,1] ,[4,2] ,[5,3]])
print("row wise sorting : ",np.sort(arr_2d , axis =0))

sorted array  [ 1  2  3  4  5 31]
row wise sorting :  [[3 1]
 [4 2]
 [5 3]]


### filtering 

In [7]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = array[array % 2 == 0 ]
print("even numbers are : " , even_numbers)

even numbers are :  [ 2  4  6  8 10]


##### filter with mask

In [8]:
mask = array > 4
print("numbers greater than 4 : ",array[mask])

numbers greater than 4 :  [ 5  6  7  8  9 10]


#### fancy indexing vs where() clause

In [24]:
indices = [0,2,4]
print(array[indices])

where_result = np.where(array > 5 )
print(where_result)
print("Np where : ",array[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np where :  [ 6  7  8  9 10]


In [30]:
condition_array = np.where(array > 5, array * 3 ,array)
print("conditional array : ",condition_array)

conditional array :  [ 1  2  3  4  5 18 21 24 27 30]


#### adding and removing data

In [9]:
# how to merge two arrays:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

adding_arr = arr1 + arr2
print(adding_arr)

combined_arr = np.concatenate((arr1,arr2))
print(combined_arr)



[5 7 9]
[1 2 3 4 5 6]


##### array compatibality

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([[4,5,6],[4,5,6]])
arr3 = np.array([[7,8,9],[7,7,8,]])

print("compatibility of array : ",arr1.shape == arr2.shape)
print("compatibility of array : ",arr1.size == arr2.size)

print("compatibility of array : ",arr2.shape == arr3.shape)
print("compatibility of array : ",arr2.size == arr3.size)

original = np.array([[1,2] , [2,3]])
new_row = np.array([4,5])
#vstack means vertical stack(it always add row)
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

#hstack means vertical stack(it always add column)
new_column = np.array([[7],[8]])
with_new_column = np.hstack((original,new_column))
print(with_new_column)

arr = np.array([1,2,3,4])
deleted = np.delete(arr,3)
print("array after deletion ",deleted)



compatibility of array :  False
compatibility of array :  False
compatibility of array :  True
compatibility of array :  True
[[1 2]
 [2 3]]
[[1 2]
 [2 3]
 [4 5]]
[[1 2 7]
 [2 3 8]]
array after deletion  [1 2 3]
