##Numpy Practice

In [1]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
print("1d array : ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array : ",arr_2d)

1d array :  [1 2 3 4 5]
2d array :  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [ ]:
py_list = [1,2,3]
print("multiplication of python list : ",py_list * 2)

np_arr = np.array([1,2,3])
print("multiplication of python array : ",np_arr * 2)

### creating array from scratch

In [ ]:
zeros = np.zeros((3,4))
print("matrix of 3 * 4 : \n", zeros)

ones = np.ones((2,4))
print("matrix of one : \n",ones)

full = np.full((2,2),6)
print("array of constant :\n",full)

random = np.random.random((2,3))
print("array of raandom numbers : \n",random)

#important one: here 9 is exclusive
sequence = np.arange(0,9,2)
print("array of sequnece numbers : \n",sequence)

matrix of 3 * 4 : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
matrix of one : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
array of constant :
 [[6 6]
 [6 6]]
array of raandom numbers : 
 [[0.96360993 0.68589934 0.70169423]
 [0.55555484 0.2272483  0.8609833 ]]
array of sequnece numbers : 
 [0 2 4 6 8]


### vector , matrix & tensor

In [3]:
vector = np.array([1,2,3]) #1 dimension is vector
print(vector)

matrix = np.array([[1,2,3],[4,5,6]]) #2d is matrix
print(matrix)

tensor = np.array([[[1,2,3],[4,5,6]],
                   [[3,4,5],[1,2,3]]])

print("\n",tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]

 [[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [1 2 3]]]


#### Array Properties

In [4]:
arr = np.array([[1,2,2],
                [3,4,5]])

print("shape of array : " ,arr.shape)
print("dimension of array : " ,arr.ndim)
print("size of array : " ,arr.size)
print("Dtype : ",arr.dtype)

shape of array :  (2, 3)
dimension of array :  2
size of array :  6
Dtype :  int64


### Array reshaping

In [ ]:
arr = np.arange(12)
print("original array ",arr)

reshaped_arr = arr.reshape((3,4))
print("reshaped array : \n",reshaped_arr)
# flatten changed the array shap to flat(1d)
flattened= reshaped_arr.flatten()
print(" flattened array : ",flattened)

#returns view instead of copy
ravelled_arr = reshaped_arr.ravel()
print("ravelled_arr",ravelled_arr)

#transpose
transpose = reshaped_arr.T
print("transpose :\n",transpose)




original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
 flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravelled_arr [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose :
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [2]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
